# Generated by Django 4.1.5 on 2023-01-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_level_player_remove_games_userid_delete_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
