# Generated by Django 4.1.5 on 2023-01-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_game_id_alter_game_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='Game_Name',
        ),
    ]
